// Auto-generated by scripts/bundle-woff2-fonts.py

export interface BundledFontEntry {
  /** Module path relative to this directory (without extension). */
  module: string;
  /** Font family name to register under. */
  registerAs: string;
  /** If this is a substitute for an Office font, the original name. */
  substituteFor?: string;
  /** Available variant names (keys exported from the module). */
  variants: string[];
}

/** All bundled font families, keyed by lowercase family name. */
export const BUNDLED_FONTS: Record<string, BundledFontEntry> = {
  'arimo': {
    module: './arimo.js',
    registerAs: 'Arimo',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'barlow': {
    module: './barlow.js',
    registerAs: 'Barlow',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'barlow light': {
    module: './barlow-light.js',
    registerAs: 'Barlow Light',
    variants: ["regular", "italic"],
  },
  'caladea': {
    module: './caladea.js',
    registerAs: 'Caladea',
    substituteFor: 'Cambria',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'calibri light': {
    module: './calibri-light.js',
    registerAs: 'Calibri Light',
    substituteFor: 'Calibri Light',
    variants: ["regular"],
  },
  'carlito': {
    module: './carlito.js',
    registerAs: 'Carlito',
    substituteFor: 'Calibri',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'comfortaa': {
    module: './comfortaa.js',
    registerAs: 'Comfortaa',
    variants: ["regular", "bold"],
  },
  'courier prime': {
    module: './courier-prime.js',
    registerAs: 'Courier Prime',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'fira code': {
    module: './fira-code.js',
    registerAs: 'Fira Code',
    variants: ["regular", "bold"],
  },
  'gelasio': {
    module: './gelasio.js',
    registerAs: 'Gelasio',
    substituteFor: 'Georgia',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'lato': {
    module: './lato.js',
    registerAs: 'Lato',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'lato light': {
    module: './lato-light.js',
    registerAs: 'Lato Light',
    variants: ["regular", "italic"],
  },
  'liberation mono': {
    module: './liberation-mono.js',
    registerAs: 'Liberation Mono',
    substituteFor: 'Courier New',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'liberation sans': {
    module: './liberation-sans.js',
    registerAs: 'Liberation Sans',
    substituteFor: 'Arial',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'liberation sans narrow': {
    module: './liberation-sans-narrow.js',
    registerAs: 'Liberation Sans Narrow',
    substituteFor: 'Arial Narrow',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'liberation serif': {
    module: './liberation-serif.js',
    registerAs: 'Liberation Serif',
    substituteFor: 'Times New Roman',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'montserrat': {
    module: './montserrat.js',
    registerAs: 'Montserrat',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'noto sans': {
    module: './noto-sans.js',
    registerAs: 'Noto Sans',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'noto sans symbols': {
    module: './noto-sans-symbols.js',
    registerAs: 'Noto Sans Symbols',
    variants: ["regular", "bold"],
  },
  'noto serif': {
    module: './noto-serif.js',
    registerAs: 'Noto Serif',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'open sans': {
    module: './open-sans.js',
    registerAs: 'Open Sans',
    variants: ["regular", "bold"],
  },
  'oswald': {
    module: './oswald.js',
    registerAs: 'Oswald',
    variants: ["regular", "bold"],
  },
  'play': {
    module: './play.js',
    registerAs: 'Play',
    variants: ["regular", "bold"],
  },
  'playfair display': {
    module: './playfair-display.js',
    registerAs: 'Playfair Display',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'poppins': {
    module: './poppins.js',
    registerAs: 'Poppins',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'raleway': {
    module: './raleway.js',
    registerAs: 'Raleway',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'roboto': {
    module: './roboto.js',
    registerAs: 'Roboto',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'roboto mono': {
    module: './roboto-mono.js',
    registerAs: 'Roboto Mono',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'roboto slab': {
    module: './roboto-slab.js',
    registerAs: 'Roboto Slab',
    variants: ["regular", "bold"],
  },
  'roboto slab light': {
    module: './roboto-slab-light.js',
    registerAs: 'Roboto Slab Light',
    variants: ["regular"],
  },
  'roboto slab semibold': {
    module: './roboto-slab-semibold.js',
    registerAs: 'Roboto Slab SemiBold',
    variants: ["regular"],
  },
  'selawik': {
    module: './selawik.js',
    registerAs: 'Selawik',
    substituteFor: 'Segoe UI',
    variants: ["regular", "bold"],
  },
  'selawik light': {
    module: './selawik-light.js',
    registerAs: 'Selawik Light',
    substituteFor: 'Segoe UI Light',
    variants: ["regular"],
  },
  'selawik semibold': {
    module: './selawik-semibold.js',
    registerAs: 'Selawik Semibold',
    substituteFor: 'Segoe UI Semibold',
    variants: ["regular"],
  },
  'selawik semilight': {
    module: './selawik-semilight.js',
    registerAs: 'Selawik Semilight',
    substituteFor: 'Segoe UI Semilight',
    variants: ["regular"],
  },
  'source code pro': {
    module: './source-code-pro.js',
    registerAs: 'Source Code Pro',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'source sans pro': {
    module: './source-sans-pro.js',
    registerAs: 'Source Sans Pro',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'tex gyre bonum': {
    module: './tex-gyre-bonum.js',
    registerAs: 'TeX Gyre Bonum',
    substituteFor: 'Bookman Old Style',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'tex gyre pagella': {
    module: './tex-gyre-pagella.js',
    registerAs: 'TeX Gyre Pagella',
    substituteFor: 'Palatino Linotype',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'tex gyre schola': {
    module: './tex-gyre-schola.js',
    registerAs: 'TeX Gyre Schola',
    substituteFor: 'Century Schoolbook',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'tinos': {
    module: './tinos.js',
    registerAs: 'Tinos',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'ubuntu': {
    module: './ubuntu.js',
    registerAs: 'Ubuntu',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'cambria': {
    module: './caladea.js',
    registerAs: 'Cambria',
    substituteFor: 'Cambria',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'calibri': {
    module: './carlito.js',
    registerAs: 'Calibri',
    substituteFor: 'Calibri',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'georgia': {
    module: './gelasio.js',
    registerAs: 'Georgia',
    substituteFor: 'Georgia',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'courier new': {
    module: './liberation-mono.js',
    registerAs: 'Courier New',
    substituteFor: 'Courier New',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'arial': {
    module: './liberation-sans.js',
    registerAs: 'Arial',
    substituteFor: 'Arial',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'arial narrow': {
    module: './liberation-sans-narrow.js',
    registerAs: 'Arial Narrow',
    substituteFor: 'Arial Narrow',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'times new roman': {
    module: './liberation-serif.js',
    registerAs: 'Times New Roman',
    substituteFor: 'Times New Roman',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'segoe ui': {
    module: './selawik.js',
    registerAs: 'Segoe UI',
    substituteFor: 'Segoe UI',
    variants: ["regular", "bold"],
  },
  'segoe ui light': {
    module: './selawik-light.js',
    registerAs: 'Segoe UI Light',
    substituteFor: 'Segoe UI Light',
    variants: ["regular"],
  },
  'segoe ui semibold': {
    module: './selawik-semibold.js',
    registerAs: 'Segoe UI Semibold',
    substituteFor: 'Segoe UI Semibold',
    variants: ["regular"],
  },
  'segoe ui semilight': {
    module: './selawik-semilight.js',
    registerAs: 'Segoe UI Semilight',
    substituteFor: 'Segoe UI Semilight',
    variants: ["regular"],
  },
  'bookman old style': {
    module: './tex-gyre-bonum.js',
    registerAs: 'Bookman Old Style',
    substituteFor: 'Bookman Old Style',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'palatino linotype': {
    module: './tex-gyre-pagella.js',
    registerAs: 'Palatino Linotype',
    substituteFor: 'Palatino Linotype',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
  'century schoolbook': {
    module: './tex-gyre-schola.js',
    registerAs: 'Century Schoolbook',
    substituteFor: 'Century Schoolbook',
    variants: ["regular", "bold", "italic", "boldItalic"],
  },
};

