/**
 * Native content stream generation — zero pdf-lib dependencies.
 */
export {
  formatNumber,
  pushGraphicsState,
  popGraphicsState,
  setGraphicsState,
  setLineWidth,
  setLineCap,
  setLineJoin,
  setDashPattern,
  concatMatrix,
  translate,
  scale,
  rotateRadians,
  skewRadians,
  moveTo,
  lineTo,
  rectangle,
  appendBezierCurve,
  closePath,
  stroke,
  fill,
  fillAndStroke,
  endPath,
  clip,
  clipEvenOdd,
  setFillingGrayscaleColor,
  setStrokingGrayscaleColor,
  setFillingRgbColor,
  setStrokingRgbColor,
  setFillingCmykColor,
  setStrokingCmykColor,
  setFillColor,
  setStrokeColor,
  beginText,
  endText,
  setFontAndSize,
  showText,
  setTextMatrix,
  rotateAndSkewTextRadiansAndTranslate,
  setTextLeading,
  nextLine,
  moveText,
  drawXObject,
  beginMarkedContent,
  endMarkedContent,
} from './operators.js';

export { ContentStreamBuilder } from './ContentStreamBuilder.js';
export type {
  DrawRectOptions,
  DrawLineOptions,
  DrawImageOptions,
  DrawTextOptions,
  DrawTextLinesOptions,
  DrawEllipseOptions,
} from './ContentStreamBuilder.js';
