/**
 * Parser entry point — tree-shakeable import for parsing-only consumers.
 *
 * Re-exports OPC reading, DrawingML parsing, theme resolution, IR types,
 * unit conversions, geometry, and font metrics. Does NOT include any
 * Canvas2D rendering code.
 *
 * Usage:
 *   import { OpcPackageReader, parseFill, parseTheme } from '@opendockit/core/parser';
 */

// OPC package reading
export {
  OpcPackageReader,
  OpcPackageWriter,
  parseContentTypes,
  serializeContentTypes,
  parseRelationships,
  serializeRelationships,
  normalizePartUri,
  resolvePartUri,
  getPartDirectory,
  getRelationshipPartUri,
  getRootRelationshipUri,
  REL_SLIDE,
  REL_SLIDE_LAYOUT,
  REL_SLIDE_MASTER,
  REL_THEME,
  REL_OFFICE_DOCUMENT,
  REL_IMAGE,
  REL_CHART,
  REL_NOTES_SLIDE,
  REL_HYPERLINK,
  REL_COMMENT_AUTHORS,
  REL_PRES_PROPS,
  REL_VIEW_PROPS,
  REL_TABLE_STYLES,
  REL_FONT,
  REL_DIAGRAM_DATA,
  REL_DIAGRAM_DRAWING,
} from '../opc/index.js';
export type {
  OpcPackage,
  ProgressEvent,
  ContentTypeMap,
  ContentTypeEntry,
  Relationship,
  RelationshipMap,
} from '../opc/index.js';

// DrawingML parsers (excludes renderers)
export {
  parseFill,
  parseLine,
  parseLineFromParent,
  parseEffectList,
  parseEffectsFromParent,
  parseTransform,
  parseTransformFromParent,
  parseGroupTransform,
  parseTextBody,
  parseTextBodyFromParent,
  parseListStyle,
  parseParagraphProperties,
  parseBulletProperties,
  parsePicture,
  parseShapeProperties,
  parseShapePropertiesFromParent,
  parseGroup,
  parseShapeTreeChildren,
  parseStyleReference,
  parseTable,
  parseTableRow,
  parseTableCell,
  parseTableCellBorders,
  parseHyperlink,
  parseDiagramDrawing,
  parseDiagramShapeTree,
} from '../drawingml/parser/index.js';
export type { GroupTransformResult } from '../drawingml/parser/index.js';

// DrawingML geometry
export {
  createGuideContext,
  evaluateFormula,
  evaluateGuides,
  getPresetGeometry,
  getPresetGeometryNames,
  buildPresetPath,
  buildPresetPaths,
  buildCustomPath,
  tracePresetPath,
  traceCustomPath,
} from '../drawingml/geometry/index.js';
export type {
  GuideContext,
  GeometrySubPath,
  PresetGeometryDef,
  PresetPath,
  PresetPathCommand,
} from '../drawingml/geometry/index.js';

// Theme parsing and resolution
export {
  parseTheme,
  resolveColor,
  resolveColorFromParent,
  resolveThemeFont,
  isThemeFontRef,
  resolveFormatStyle,
} from '../theme/index.js';
export type { ColorContext, ResolvedFormatStyle } from '../theme/index.js';

// IR types
export type {
  RgbaColor,
  ResolvedColor,
  BoundingBox,
  Point,
  Size,
  HyperlinkIR,
  TransformIR,
  SolidFillIR,
  GradientStopIR,
  GradientFillIR,
  PatternFillIR,
  PictureFillIR,
  NoFill,
  FillIR,
  DashStyle,
  LineCap,
  LineJoin,
  CompoundLine,
  LineEnd,
  LineIR,
  OuterShadowIR,
  InnerShadowIR,
  GlowIR,
  ReflectionIR,
  SoftEdgeIR,
  EffectIR,
  ShapeGuideIR,
  AdjustHandleIR,
  ConnectionSiteIR,
  MoveToCommand,
  LineToCommand,
  ArcToCommand,
  CubicBezierToCommand,
  QuadBezierToCommand,
  CloseCommand,
  PathCommandIR,
  ShapePathIR,
  PresetGeometryIR,
  CustomGeometryIR,
  GeometryIR,
  StyleReferenceIR,
  ShapePropertiesIR,
  TextBodyIR,
  BodyPropertiesIR,
  TabStopIR,
  SpacingIR,
  ParagraphIR,
  ParagraphPropertiesIR,
  UnderlineStyle,
  CharacterPropertiesIR,
  RunIR,
  LineBreakIR,
  BulletPropertiesIR,
  ListStyleLevelIR,
  ListStyleIR,
  CropRect,
  TileInfo,
  PictureIR,
  GroupIR,
  ConnectionReference,
  ConnectorIR,
  TableCellBorders,
  TableCellMargins,
  TableCellIR,
  TableRowIR,
  TableIR,
  DrawingMLShapeIR,
  UnsupportedIR,
  SlideElementIR,
  ColorSchemeIR,
  FontSchemeIR,
  FormatSchemeIR,
  ThemeIR,
  ChartIR,
} from '../ir/index.js';

// Units
export type { EMU, HundredthsPt, Pixels } from '../units/index.js';
export {
  emu,
  hundredthsPt,
  pixels,
  isValidEmu,
  emuChecked,
  EMU_PER_INCH,
  EMU_PER_PT,
  EMU_PER_CM,
  EMU_PER_MM,
  EMU_PER_PX_96DPI,
  EMU_PER_DXA,
  emuToIn,
  emuToPt,
  emuToCm,
  emuToMm,
  emuToPx,
  inToEmu,
  ptToEmu,
  cmToEmu,
  mmToEmu,
  pxToEmu,
  DXA_PER_PT,
  DXA_PER_INCH,
  DXA_PER_CM,
  dxaToPt,
  dxaToPx,
  dxaToIn,
  dxaToCm,
  dxaToEmu,
  ptToDxa,
  inToDxa,
  halfPointsToPt,
  ptToHalfPoints,
  hundredthsPtToPt,
  ptToHundredthsPt,
  ooxml60kToRadians,
  ooxml60kToDegrees,
  degreesToOoxml60k,
  radiansToOoxml60k,
  ooxmlPercentToFraction,
  fractionToOoxmlPercent,
} from '../units/index.js';

// Font metrics and resolution
export {
  getFontSubstitution,
  resolveFontName,
  estimateTextWidth,
  getLineHeight,
  getAverageCharWidthRatio,
  isFontAvailable,
  loadFont,
  ensureFontLoaded,
  FontMetricsDB,
  extractFontFromEot,
  deobfuscateOdttf,
  isGoogleFont,
  loadGoogleFont,
  loadGoogleFonts,
  hasOflSubstitute,
  getOflSubstituteFamily,
  loadOflSubstitute,
  loadOflSubstitutes,
  hasBundledFont,
  loadBundledFont,
  loadBundledFonts,
  hasTTFBundle,
  loadTTF,
  clearTTFCache,
  FontResolver,
  FontCache,
  fetchFromFontsource,
  fetchFromGoogleFonts,
  SUBSTITUTION_REGISTRY,
} from '../font/index.js';
export type {
  FontFaceMetrics,
  FontMetricsBundle,
  FontConfig,
  FontRegistration,
  FontSource,
  FontResolutionStatus,
  FontProgressEvent,
  SubstitutionEntry,
} from '../font/index.js';
